---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ginuudan
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
    verbs:
      - create
      - list
      - watch
      - update
      - patch

  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - patch

  - apiGroups:
      - ""
    resources:
      - pods/exec
      - pods/portforward
    verbs:
      - create
      - get
      - list
