apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ginuudan
  labels:
    team: aura
spec:
  image: ghcr.io/nais/ginuudan/ginuudan:2021-07-23-ac17ec6
  replicas:
    min: 1
    max: 1
  strategy:
    type: Recreate
  prometheus:
    enabled: true
    path: /
    port: "9090"
