apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ginuudan
  namespace: aura
  labels:
    team: aura
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
  strategy:
    type: Recreate
