name: build and push
on: 
  push:
    branches:
      - main
env:
  GINUUDAN_IMAGE: ghcr.io/${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: docker/setup-buildx-action@v1
      - run: echo "IMAGE=${GINUUDAN_IMAGE}:$(date '+%Y-%m-%d')-$(git --no-pager log -1 --pretty=%h)" >> $GITHUB_ENV
      - uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06 # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

  nais-yaml:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout ginuudan
        uses: actions/checkout@v2
        with:
          path: ginuudan
      - name: Checkout nais-yaml
        uses: actions/checkout@v2
        with:
          repository: navikt/nais-yaml
          token: ${{ secrets.REPO_PUSH_PAT }}
          path: nais-yaml
      - run: |
          cd naiserator
          echo "VERSION=$(date '+%Y-%m-%d')-$(git --no-pager log -1 --pretty=%h)" >> $GITHUB_ENV
          echo "IMAGE=${GINUUDAN_IMAGE}:${VERSION}" >> $GITHUB_ENV
      - run: |
          cd naiserator
          res=".nais"
          static_file="../nais-yaml/templates/zz-generated-ginuudan.yaml"
          cat $res/clusterrole.yaml $res/clusterrolebinding.yaml > $static_file
      - run: |
          cd nais-yaml
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          sed -E -i "s#image: ${GINUUDAN_IMAGE}:.+#image: ${IMAGE}#" vars/global.yaml
          git add .
          git --no-pager diff --cached
          git status
          git commit -a -m "Bump Ginuudan to version ${VERSION}"
          git push
